#!/bin/bash

# sh7. for
<< FOR_1
for n in 1 3 5 7 9 2 4 6 8 10
do 
	echo $n
# done
# done | sort -n 	# pipe 
# done > a.txt		# redirection  
done &				# run background

echo "aaa"
FOR_1

# IFS (Intermediate field separator
IFS=":" 
for n in 1:2:3:4
do 
	echo "$n"
done

<< FOR_4
#
for n in *
do 
	echo $n
done

for n in $(ls -al)
do 
	echo $n
done

FOR_4

# bash 
i=0

for (( i = 0; i < 10; i++ ))
do 
	echo $i
done




