#!/bin/bash

# FTP 서버 설치 : sudo apt-get install vsftpd

#awk_test

# 수많은 화일 중에 원하는 파일을 찾고(find), 해당 파일에서 원하는 문자열 검색 후 (grep)
# 보기 좋은 형태로 출력 report 작성 또는 DB 에 넣기... (awk 툴 사용)

# awk : 데이터 프로세싱, 리포트 작성, 간단한 DB 구축, 약자는 개발자 이름임.

# 0. 테스트 파일 준비
#ps -ef > ps.txt

#less ps.txt # 파일 확인

# 1. 기본 모양
#awk '{print $8}' ps.txt 			# 8번째 필드만 출력 : awk '{명령어 또는 제어문}' 파일명
#awk '{print $1, $8}' ps.txt		# , : 각 필드를 OFS - output field seperator 변수의 값으로 분리해 달라(default: ' ')
#awk '{print NR, $8}' ps.txt		# NR : awk 의 내장 변수, 줄 번호 
#awk '{print NR " : " $8}' ps.txt	# 문자열 끼리 연결 가능
#awk '{printf "%05s : %s \n", NR, $8}' ps.txt # print 대신 printf 도 사용 가능


# 2. 파일이 아닌 파이프 라인 data 처리
#date 			# 날짜 출력하는 쉘 명령어
#date +%F		# 다양한 옵현은 - man date 참고
				# 2015-11-02
# 쉘 명령어의 출력 결과를 원하는 형태로 제공

#date +%F | awk -F'-' '{print $1"년", $2"월", $3"일"}' 	# 파이프로 입력 data가 오게 되므로 파일 이름은 필요 없음.
														# -F : 필드 구분자 변경
														# 필드 구분자가 2문자 이상이면 ' '


#date +%F | awk -F'[- ]' '{print $1"년", $2"월", $3"일"}' # FS(field seperator)로 정규 표현식도 가능!
#date +%F | awk -F'[- ]' '{printf "%s년 %s월 %s일", $1, $2, $3}'

# /etc/passwd 파일에서 ID와 UID만 화면에 출력해 보세요
# less /etc/passwd 로 내용 확인 
# ID (문자열 계정), UID (숫자)
echo "ID	UID"
awk -F: '{printf "%s\t%s\n", $1, $3}' /etc/passwd




